/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  rous
 * Created: 22/11/2016
 */
/*
    Tabla book
*/
use library;
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('796389130-4', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Raymond Freeman', 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget', 'Al-Nasser University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('718070118-1', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Kevin Owens', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis', 'Technical University of Bialystok');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('883979586-3', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Clarence Montgomery', 'in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 'Universidad Iberoamericana, Campus León');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('062023647-7', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Kenneth Murray', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', 'Purdue University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('871571576-0', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Steven Holmes', 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 'Georgetown University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('931693436-2', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Joshua Bailey', 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 'Universidad Nacional del Altiplano');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('073848923-9', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Diana Lopez', 'nulla pede ullamcorper', 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 'Qiongzhou University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('325248147-2', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Annie Adams', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae', 'in est risus auctor sed tristique in tempus sit amet sem fusce', 'Universidad Católica Anselmo Llorente');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('368025822-4', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Teresa Gordon', 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum', 'Kanazawa Medical University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('431503554-8', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Shirley Montgomery', 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 'Shaoguan University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('008928893-9', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Peter Coleman', 'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed', 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', 'Universidad Nacional Autónoma de Honduras');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('085036700-X', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Phyllis Willis', 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id', 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet', 'St. John''s College Maryland');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('862441131-9', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Nicholas Howard', 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue', 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', 'Universidad de Deusto');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('579196670-9', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Joseph Kim', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget', 'risus auctor sed tristique in tempus sit amet sem fusce consequat', 'Estonian University of Life Sciences');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('621520037-9', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Sarah Turner', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', 'Universidad Dominicana O&M');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('350318589-5', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Lisa Davis', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 'Lindenwood University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('056039184-6', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Roger Parker', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', 'Houston Baptist University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('453253311-2', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Shawn Stevens', 'lobortis ligula sit', 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 'The Johns Hopkins University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('728420966-6', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Frances Spencer', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh', 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', 'Sichuan International Studies University');
insert into Book (book_isbn, book_title, book_author, book_abstract, book_cover, book_editorial) values ('526191534-1', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Thomas Weaver', 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 'Hamamatsu University');
