-- MySQL Script generated by MySQL Workbench
-- mar 15 nov 2016 10:32:54 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Yii
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Yii` ;

-- -----------------------------------------------------
-- Schema Yii
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yii` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Category` (
  `cat_name` VARCHAR(20) NOT NULL,
  `cat_descrption` VARCHAR(400) NULL,
  PRIMARY KEY (`cat_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_isbn` VARCHAR(13) NOT NULL,
  `book_title` VARCHAR(45) NOT NULL,
  `book_author` VARCHAR(45) NULL,
  `book_abstract` VARCHAR(500) NULL,
  `book_cover` VARCHAR(200) NULL,
  `book_editorial` VARCHAR(45) NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Book_has_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Book_has_Category` (
  `book_id` INT NOT NULL,
  `cat_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`book_id`, `cat_name`),
  INDEX `fk_Book_has_Category_Category1_idx` (`cat_name` ASC),
  INDEX `fk_Book_has_Category_Book_idx` (`book_id` ASC),
  CONSTRAINT `fk_Book_has_Category_Book`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_Category_Category1`
    FOREIGN KEY (`cat_name`)
    REFERENCES `library`.`Category` (`cat_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Copy` (
  `copy_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `copy_edition` ENUM('First', 'Second', 'Third', 'Fourth', 'Fifth') NOT NULL,
  `copy_language` ENUM('Spanish', 'English', 'Chinese', 'Russian', 'Arabic', 'Portuguese', 'French', 'Japanese', 'Turkish', 'German') NULL DEFAULT 'English',
  `copy_available` TINYINT(1) NULL DEFAULT 1,
  `copy_state` ENUM('Ok', 'Damaged', 'Incomplete') NULL DEFAULT 'Ok',
  PRIMARY KEY (`copy_id`),
  INDEX `fk_Copy_Book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_Copy_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_names` VARCHAR(100) NOT NULL,
  `user_lastname` VARCHAR(45) NOT NULL,
  `user_snd_lastname` VARCHAR(45) NOT NULL,
  `user_curp` VARCHAR(18) NOT NULL,
  `user_email` VARCHAR(70) NOT NULL,
  `user_telephone` VARCHAR(15) NOT NULL,
  `user_address` VARCHAR(100) NOT NULL,
  `user_profile_photo` VARCHAR(200) NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `password_hash` VARCHAR(255) NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `status` SMALLINT(6) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Lending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Lending` (
  `user_id` INT NOT NULL,
  `copy_id` INT NOT NULL,
  `lend_auth_at` DATETIME NOT NULL,
  `lend_return_at` DATETIME NOT NULL,
  `lend_return_real` DATETIME NULL,
  PRIMARY KEY (`user_id`, `copy_id`),
  INDEX `fk_User_has_Copy_Copy1_idx` (`copy_id` ASC),
  INDEX `fk_User_has_Copy_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Copy_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `library`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Copy_Copy1`
    FOREIGN KEY (`copy_id`)
    REFERENCES `library`.`Copy` (`copy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Yii` ;

-- -----------------------------------------------------
-- Table `Yii`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`Personas` (
  `id_personas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_persona` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `ap_pat_persona` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `ap_mat_persona` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_personas`))
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`Direcciones` (
  `id_Direccion` INT(11) NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `colonia` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `codigo_postal` INT(5) NOT NULL,
  `tipo` ENUM('casa', 'oficina', 'negocio') CHARACTER SET 'utf8' NOT NULL,
  `id_persona` INT(11) NOT NULL,
  PRIMARY KEY (`id_Direccion`),
  INDEX `fk_Direcciones_1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_Direcciones_1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `Yii`.`Personas` (`id_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`Redes_Sociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`Redes_Sociales` (
  `id_red_social` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Facebook', 'Gmail', 'GitHub', 'Instagram') CHARACTER SET 'utf8' NOT NULL,
  `cuenta` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `id_persona` INT(11) NOT NULL,
  PRIMARY KEY (`id_red_social`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`Telefono` (
  `id_telefono` INT(11) NOT NULL AUTO_INCREMENT,
  `contacto` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `typo_telefono` ENUM('casa', 'movil', 'oficina') CHARACTER SET 'utf8' NOT NULL,
  `id_persona` INT(11) NOT NULL,
  `numero` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_telefono`),
  INDEX `fk_Telefono_1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_Telefono_1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `Yii`.`Personas` (`id_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `type` (`type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `Yii`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `child` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `Yii`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `Yii`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`companies` (
  `company_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '	',
  `company_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `company_email` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `company_address` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `company_create_date` DATETIME NOT NULL,
  `company_status` ENUM('active', 'inactive') CHARACTER SET 'utf8' NOT NULL,
  `company_start_date` DATETIME NOT NULL,
  `company_logo` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`branches` (
  `branch_id` INT(11) NOT NULL AUTO_INCREMENT,
  `companies_company_id` INT(11) NOT NULL,
  `branch_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `branch_address` VARCHAR(225) CHARACTER SET 'utf8' NOT NULL,
  `branch_create_date` DATETIME NOT NULL,
  `branch_status` ENUM('active', 'inactive') CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `fk_branches_1_idx` (`companies_company_id` ASC),
  CONSTRAINT `fk_branches_1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `Yii`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`correos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`correos` (
  `id_correo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('personal', 'oficina') CHARACTER SET 'utf8' NOT NULL,
  `cuenta` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `id_persona` INT(11) NOT NULL,
  PRIMARY KEY (`id_correo`),
  INDEX `fk_correos_1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_correos_1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `Yii`.`Personas` (`id_personas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`customers` (
  `customers_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `zip_code` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `city` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `province` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`customers_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`departments` (
  `department_id` INT(11) NOT NULL AUTO_INCREMENT,
  `branches_branch_id` INT(11) NOT NULL,
  `department_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `companies_company_id` INT(11) NOT NULL,
  `department_create_date` DATETIME NOT NULL,
  `department_status` ENUM('active', 'inactive') CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`department_id`),
  INDEX `fk_departments_1_idx` (`companies_company_id` ASC),
  INDEX `fk_departments_2_idx` (`branches_branch_id` ASC),
  CONSTRAINT `fk_departments_1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `Yii`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_2`
    FOREIGN KEY (`branches_branch_id`)
    REFERENCES `Yii`.`branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`emails` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `receiver_name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `receiver_email` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `subject` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `content` TEXT CHARACTER SET 'utf8' NOT NULL,
  `attachment` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' NOT NULL,
  `create_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`locations` (
  `locations_id` INT(11) NOT NULL AUTO_INCREMENT,
  `zip_code` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `city` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `province` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`locations_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`migration` (
  `version` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`po`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`po` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `po_no` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`po_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`po_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `po_item_no` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `quatity` DOUBLE NOT NULL,
  `po_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_po_item_1_idx` (`po_id` ASC),
  CONSTRAINT `fk_po_item_1`
    FOREIGN KEY (`po_id`)
    REFERENCES `Yii`.`po` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Yii`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yii`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  `first_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `last_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
