-- MySQL Script generated by MySQL Workbench
-- 11/16/16 04:13:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Category` (
  `cat_name` VARCHAR(20) NOT NULL,
  `cat_descrption` VARCHAR(400) NULL,
  PRIMARY KEY (`cat_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_isbn` VARCHAR(13) NOT NULL,
  `book_title` VARCHAR(45) NOT NULL,
  `book_author` VARCHAR(45) NULL,
  `book_abstract` VARCHAR(500) NULL,
  `book_cover` VARCHAR(200) NULL,
  `book_editorial` VARCHAR(45) NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Book_has_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Book_has_Category` (
  `book_id` INT NOT NULL,
  `cat_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`book_id`, `cat_name`),
  INDEX `fk_Book_has_Category_Category1_idx` (`cat_name` ASC),
  INDEX `fk_Book_has_Category_Book_idx` (`book_id` ASC),
  CONSTRAINT `fk_Book_has_Category_Book`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_Category_Category1`
    FOREIGN KEY (`cat_name`)
    REFERENCES `library`.`Category` (`cat_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Copy` (
  `copy_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `copy_edition` ENUM('First', 'Second', 'Third', 'Fourth', 'Fifth') NOT NULL,
  `copy_language` ENUM('Spanish', 'English', 'Chinese', 'Russian', 'Arabic', 'Portuguese', 'French', 'Japanese', 'Turkish', 'German') NULL DEFAULT 'English',
  `copy_available` TINYINT(1) NULL DEFAULT 1,
  `copy_state` ENUM('Ok', 'Damaged', 'Incomplete') NULL DEFAULT 'Ok',
  PRIMARY KEY (`copy_id`),
  INDEX `fk_Copy_Book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_Copy_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_names` VARCHAR(100) NOT NULL,
  `user_lastname` VARCHAR(45) NOT NULL,
  `user_snd_lastname` VARCHAR(45) NOT NULL,
  `user_curp` VARCHAR(18) NOT NULL,
  `user_email` VARCHAR(70) NOT NULL,
  `user_telephone` VARCHAR(15) NOT NULL,
  `user_address` VARCHAR(100) NOT NULL,
  `user_profile_photo` VARCHAR(200) NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `password_hash` VARCHAR(255) NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `status` SMALLINT(6) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Lending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Lending` (
  `user_id` INT NOT NULL,
  `copy_id` INT NOT NULL,
  `lend_auth_at` DATETIME NOT NULL,
  `lend_return_at` DATETIME NOT NULL,
  `lend_return_real` DATETIME NULL,
  PRIMARY KEY (`user_id`, `copy_id`),
  INDEX `fk_User_has_Copy_Copy1_idx` (`copy_id` ASC),
  INDEX `fk_User_has_Copy_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Copy_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `library`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Copy_Copy1`
    FOREIGN KEY (`copy_id`)
    REFERENCES `library`.`Copy` (`copy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `library`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`User` (`user_id`, `user_names`, `user_lastname`, `user_snd_lastname`, `user_curp`, `user_email`, `user_telephone`, `user_address`, `user_profile_photo`, `created_at`, `updated_at`, `password_hash`, `auth_key`, `password_reset_token`, `status`) VALUES (DEFAULT, 'Ivan', 'Romero', 'García', 'X', 'ivan@gmail.com', '222222222', 'Algún sitio', NULL, 1, NULL, '$2y$13$fyVoplzJM/zMQ/DIk2EzSuPHS/xWVxK8iO8TzukEN4QqjsVtYiIdi', 'q3o7Sy8UyjB0vSDDUiMcxNkMn9STuRA-', NULL, 10);
INSERT INTO `library`.`User` (`user_id`, `user_names`, `user_lastname`, `user_snd_lastname`, `user_curp`, `user_email`, `user_telephone`, `user_address`, `user_profile_photo`, `created_at`, `updated_at`, `password_hash`, `auth_key`, `password_reset_token`, `status`) VALUES (DEFAULT, 'Victor Daniel', 'Rebolloso', 'Degante', 'X', 'vrebo.deg@gmail.com', '222222222', 'Algún sitio', NULL, 1, NULL, '$2y$13$aapJkj3OpNKndf0kF8s13uPXZxsQKtOyF0caYduQEG.v7JZGHjXou', 'CsuJYcqW2LuBuRUW9OXtW7yQE_R5U0ui', NULL, 10);

COMMIT;

